packages/server/README.md
packages/server/src/api.ts
packages/server/src/broadcaster/api.ts
packages/server/src/broadcaster/index.ts
packages/server/src/factory.ts
packages/server/src/index.ts
packages/server/src/models/WHIPResource.ts
packages/server/src/server.ts
packages/server/src/wrtc/broadcaster.ts
packages/server/src/wrtc/dummy.ts
packages/server/src/wrtc/rtsp.ts

This PR addresses #17 and adds the support to configure STUN/TURN servers to use on the server peer.

feat: #17 ability to configure STUN/TURN servers on server setup

---

packages/server/src/models/WHIPResource.ts
packages/server/src/wrtc/broadcaster.ts

This PR adds support for implementing a connect and disconnect handler in WHIP resource subclasses, and resolves #5

fix: remove broadcaster channel on disconnect

---

packages/server/src/api.ts
packages/server/src/index.ts
packages/server/src/models/WHIPResource.ts

This PR adds support for returning STUN/TURN list on OPTIONS and POST response as requested in #11

feat: return STUN/TURN list in header for OPTIONS and POST response

---

packages/demo/src/index.ts
packages/sdk/README.md
packages/sdk/src/index.ts
packages/server/README.md
packages/server/src/api.ts
packages/server/src/index.ts

This PR adds support for a client to prefect ICE server configuration from endpoint as addressed in #22

feat: prefetch ICE server config from endpoint

---

packages/demo/src/index.ts
packages/server/README.md
packages/server/src/api.ts
packages/server/src/index.ts
packages/server/src/server.ts

This resolves #24 and is a breaking change as the resource location now includes server address

fix!: location header now includes server address in WHIP resource URI

---

packages/demo/package-lock.json
packages/demo/package.json
packages/demo/src/index.html
packages/demo/src/index.ts
packages/sdk/package-lock.json
packages/sdk/src/index.ts
packages/server/package-lock.json
packages/server/src/api.ts
packages/server/src/index.ts
packages/server/src/models/WHIPResource.ts
packages/server/src/wrtc/broadcaster.ts

Need to clean this up a bit but the general idea is there.

feat!: destroy resource

---

packages/sdk/README.md

This PR updates the SDK README to reflect the new SDK API changes.

fix: updated SDK documentation to reflect the new API

---

packages/demo/package-lock.json
packages/demo/package.json
packages/demo/src/index.ts
packages/demo/src/util.ts
packages/sdk/src/index.ts

This PR addresses the issue when it can take a long time until all ICE candidate checks will timeout (up to 40 seconds).
It also introduces an init() that can be called to fetch ICE config from server when SDK is initiated and before an ingest is requested.

feat!: ICE gathering timeout

---

packages/server/src/broadcaster/api.ts

This PR resolves an issue where system resources were not released.

fix: must remove track from senders when watcher disconnects

---

packages/sdk/src/index.ts

ICE gathering state transitions to complete only once and is more commonly used for detecting the end of gathering when we don't support trickle-ICE.

Suggestion: Using ICE gathering state change to detect gathering complete

---

packages/server/package.json
packages/server/src/broadcaster/index.ts
packages/server/src/broadcaster/viewer.ts
packages/server/src/models/WHIPResource.ts
packages/server/src/server.ts

This PR addresses potential resource leaking when sender or watcher disconnects. Verified by taking heap snapshots before and after:
- Start ingesting
- 1 viewer
- 2 viewers
- Close browser tabs

chore: profiling and resource leakage investigation

---

packages/server/README.md
packages/server/src/api.ts
packages/server/src/broadcaster/api.ts
packages/server/src/broadcaster/index.ts
packages/server/src/index.ts
packages/server/src/server.ts

This PR adds the possibility to set hostname and interface IP. Also fixes some missing typescript typings

feat!: ability to set hostname and interface IP

---

.dockerignore
Dockerfile
docker-compose.yml
package.json
packages/server/package.json
packages/server/src/server.ts

This PR enables building docker image of endpoint

chore: building docker image

---

packages/sdk/package.json
packages/sdk/src/WHIPProtocol.ts
packages/sdk/src/index.ts
packages/server/package.json
packages/server/src/api.ts
packages/server/src/index.ts
packages/server/src/models/WHIPResource.ts

https://github.com/Eyevinn/whip/issues/9

feat: trickle ICE from client

---

aws/ecs/taskdef-dev.json
packages/server/src/broadcaster/channel.ts
packages/server/src/broadcaster/index.ts
packages/server/src/server.ts

This PR adds the possibility to insert a pre-roll MPD period, and moves the WebRTC stream to the AdaptationSet of a period

feat: multi-period MPD

---

package.json
packages/demo/src/index.ts
packages/sdk/karma.conf.js
packages/sdk/package.json
packages/sdk/spec/WHIPClient.spec.ts
packages/sdk/src/index.ts
packages/sdk/tsconfig.json
packages/server/package.json

Add unit test framework + some basic tests for sdk.

feat: unit test framework for sdk

---

packages/demo/src/index.ts
packages/server/src/api.ts
packages/server/src/broadcaster/index.ts
packages/server/src/factory.ts
packages/server/src/wrtc/broadcaster.ts

This PR implements the functionality requested in #60

feat: request a fixed channel name

---

packages/demo/src/index.ts
packages/demo/src/util.ts
packages/demo/src/watch.ts
packages/server/README.md
packages/server/src/broadcaster/ViewerRequests.ts
packages/server/src/broadcaster/api.ts
packages/server/src/broadcaster/channel.ts
packages/server/src/broadcaster/index.ts
packages/server/src/broadcaster/viewer.ts

Server side implementation of https://github.com/Eyevinn/webrtc-http-playback-protocol/blob/master/webrtc-http-playback-protocol.md

feat: update viewer protocol based on webrtc-http-playback-protocol

---

packages/sdk/src/WHIPProtocol.ts
packages/sdk/src/index.ts
packages/server/src/api.ts
packages/server/src/index.ts
packages/server/src/models/WHIPResource.ts

closes https://github.com/Eyevinn/whip/issues/56

feat: add entity-tag header support

---

packages/server/src/broadcaster/api.ts

fix: WHPP content type

---

package-lock.json
packages/demo/package-lock.json
packages/demo/package.json
packages/demo/src/index.html
packages/demo/src/index.ts
packages/server/src/api.ts
packages/server/src/factory.ts
packages/server/src/server.ts
packages/server/src/wrtc/rtmp.ts

feat: RTMP module for restreaming to RTMP endpoint

---

packages/server/src/whpp/sfu/sfuWhppViewer.ts
packages/server/src/whpp/whppFastifyApi.ts

fix: return error code if PATCH is not supported

---

packages/server/src/broadcaster.ts
packages/server/src/whpp/sfu/sfuWhppViewer.ts
packages/server/src/whpp/whppFastifyApi.ts
packages/server/src/whpp/whppViewer.ts
packages/server/src/whpp/wrtc/wrtcWhppViewer.ts

fix: WHPP viewer endpoint should signal if PATCH method is allowed

---

packages/server/src/smb/smbProtocol.ts
packages/server/src/whip/sfu/sfuWhipResource.ts
packages/server/src/whpp/sfu/sfuWhppViewer.ts

fix: fix formatting issue with srflx candidates

---

packages/server/src/whip/whipFastifyApi.ts

fix: include accept-post header in options response

---

packages/sdk/spec/WHIPClient.spec.ts
packages/sdk/src/index.ts

I think this will be enough but couldn't get the demo to run with camera ingest to confirm all states.

added: method get peer connection property for WHIPclient class

---

packages/sdk/README.md
packages/sdk/src/index.ts
packages/sdk/typedoc.json

First take on how autogen documentation can look with code examples

chore: updated documentations to include code examples

---

multi-sfu-config.json
package.json
packages/server/README.md
packages/server/package-lock.json
packages/server/package.json
packages/server/src/server.ts
packages/server/src/whip/resourceManagerClient.ts
packages/server/src/whip/whipEndpoint.ts
sfu-config.json

Includes: 
- It is now possible to get sfu config data from a resource manager.
- Updated README with how to enable the use of the resource manager.

feat: implemented getting sfu-config data from resource manager

---

packages/demo/src/index.ts

- Actually use the provided authorization value provied by the user

chore: demo page fixes
